---
title: "Final Project Template"
author: Dr. Sandholtz
output: pdf_document
---

```{=html}
<style type="text/css">
h1.title {
font-size: 40px;
text-align: center;
}
h4.author {
font-size: 40px;
text-align: center;
}
</style>
```
\newpage

```{r setup, include=FALSE}
# load all necessary packages here
```

# Abstract

Here, you will briefly summarize the entire report, including the data used, questions of interest, and relevant findings.

# 1 Problem and Motivation

In this section, you will describe the background information about the study that is necessary to understand why the data are important. In other words, why was it important to gather the data in the first place?

## 1.1 Data Description

Briefly state the source of your data and describe the relevant variables that **you will use** in your project. Include important details such as units for the different variables, and what the \`\`observational units" (rows in the data set) represent (e.g., individuals, countries, etc.)

Our data was collected by wildlife researchers, on Southern Victoria to central Queensland

## 1.2 Questions of Interest

*Briefly and clearly state the two main questions that you will investigate throughout the report.*

*These questions should be stated in scientific, and not statistical language. For example, "Is the slope of log of per capita GDP significantly different from zero?" should instead by give as "Does the log of per capita GDP have an effect on the average life expectancy of females in a given country?"*

Question 1: Does the length of a possum's tail have an effect on the total length of the possum

Question 2:

## 1.3 Regression Methods

*For each question of interest listed in Section 2, describe what regression models, techniques, and tools you will use to fully answer it. These should include any plots you will use for exploratory analysis or diagnostic checks, as well as methods of inference you will use.*

Question 1: To determine if the site of a possum's capture has an effect on the total length of the possum we implemented a multiple linear regression model. Using the site a possum was caught at, the chest size of the possum, the head length, the tail length. Using best subset with a metric of AIC as the variable selection method is how we determined which variables to build our model on. Since site is categorical variable we encode it as a factor and proceed to check assumptions.

We first checked for multicolinearity using a correlation matrix, once satisfied that multicolinearty would not be an issue, we fit a tentative model and used it to find and save the residual values. Conducting a more thorough inspection of variables and their correlation we performed some variable inflation factor calculations. The mean of the VIFs was 1.90and the max VIF was 2.08, both indicate that we can continue the analysis under the assumption that the no multicolinearity is met. Another assumption we check was that the residuals are normally distributed, creating a density plot we are able to see that they are shaped like a normal distribution, and continue noting that this assumption was met. We performed other checks on residuals as well and the accompanying plots are show below. Finally we checked for influential points, using a Cook's distance plot we were able to see that all data points were within bounds meaning that none of them could be considered influential

# 2 Analyses, Results, and Interpretation

Conduct the analysis in a logical fashion, including necessary code (and not any superfluous code) and its output. Give simple interpretations of your findings related to the questions of interest.

# 3 Conclusions

Give additional context to you results and interpretations from Section 5 with respect to the data set and its purpose. Describe any potential weaknesses in your analysis, and how they may affect the reliability of the results.

# 4 Contributions

For each member of the group, write a short paragraph describing their contribution to this project and the report. It is up to you to decide how to divide up the work, so long as everyone is contributing approximately equally.

## APPENDIX

If there are any analyses, such as exploratory plots/summaries or work you did to determine appropriate transformations, or any relevant material that does not belong in one of the sections above, these can go in the Appendix. If you don't have any material like this, you can remove this section.
